spring:
  application:
    name: gateway-microservice
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/product/**
            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/user/**
            - id: order-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/order/**,/api/v1/cart/**
# http://localhost:8080/api/v1/user -> http://localhost:8082/api/v1/user
# http://localhost:8080/api/v1/order -> http://localhost:8083/api/v1/order
# http://localhost:8080/api/v1/product -> http://localhost:8081/api/v1/product
server:
  port: 8080

## Actuator expose all end points
management:
  endpoints: 
    web: 
      exposure: 
        include: "*"
  tracing: 
    sampling: 
      probability: 1.0
