spring:
  application:
    name: order-microservice
  datasource:
    url: jdbc:mysql://localhost:3307/orderDB
    username: embarkx
    password: embarkx
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083

#Test Rate Limiting
app: 
  message: Hello Order Service
## Actuator expose all end points
management:
  endpoints: 
    web: 
      exposure: 
        include: "*"
  endpoint:
    health: 
      show-details: always
  health: 
    circuitbreakers:
      enabled: true
  tracing: 
    sampling: 
      probability: 1.0
        
## this property is just to demo for @ConfigurationProperties
build:
  id: 001
  name: Build_EComm
  
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: localhost:${spring.application.name}:${server.port}

logging: 
  level: 
    root: INFO
  file: 
    name: logs/order-microservice.log
  logback:
    rollingpolicy: 
      max-file-size: 5MB
      max-history: 7 ## keep logs for 7 days

# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based
  retry:
    instances:
      retryBreaker:
        maxAttempts: 5
        waitDuration: 5s
  ratelimiter:
    instances:
      rateBreaker:
        timeout-duration: 0
        limit-refresh-period: 4s
        limit-for-period: 2
        
## Dummy value to test @Refresh Scope 
embarkx:
  check: 
    refreshScope: 
      value : 1

