spring:
  application:
    name: order-microservice
  datasource:
    url: jdbc:mysql://localhost:3307/orderDB
    username: embarkx
    password: embarkx
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083

## this property is just to demo for @ConfigurationProperties
build:
  id: 001
  name: Build_EComm

## Enable @Refresh Scope
management: 
  endpoints: 
    web: 
      exposure: 
        include: refresh
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance: 
    instance-id: localhost:${spring.application.name}:${server.port}

logging: 
  level: 
    root: INFO
  file: logs/order-microservice.log
  
## Dummy value to test @Refresh Scope 
embarkx:
  check: 
    refreshScope: 
      value : 1

